# Generated by Django 2.2 on 2019-04-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword1', models.CharField(max_length=200)),
                ('keyword2', models.CharField(max_length=200)),
                ('keyword3', models.CharField(max_length=200)),
                ('keyword4', models.CharField(max_length=200)),
                ('keyword5', models.CharField(max_length=200)),
                ('keyword6', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('posted_date', models.DateField(null=True)),
                ('place_of_performance_state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona')], max_length=30)),
                ('place_of_performance_zip_code', models.IntegerField()),
                ('documents_to_search', models.CharField(choices=[('Competitive 8(a)', 'Competitive 8(a)'), ('Partial HBCU / MI', 'Partial HBCU / MI'), ('Partial Small Business', 'Partial Small Business')], max_length=30)),
                ('set_aside_code', models.CharField(choices=[('Active Documents', 'Active Documents'), ('Archived Documents', 'Archived Documents'), ('Both', 'Both')], max_length=30)),
                ('j_and_a_statutory_authority', models.CharField(choices=[('FAR_63021c_Brand_name', 'FAR 6.302-1(c) - Brand name'), ('FAR_63022_Unusual_compelling', 'FAR 6.302-2 - Unusual and compelling')], max_length=30)),
                ('fair_opportunity_limited_source_justification_authority', models.CharField(choices=[('Urgency', 'Urgency'), ('Minimum Guarantee', 'Minimum Guarantee'), ('Other Statutory Authority', 'Other Statutory Authority')], max_length=30)),
                ('posted_date_range', models.DateField(null=True)),
                ('response_deadline', models.DateField(null=True)),
                ('last_modified', models.DateField(null=True)),
                ('contract_award_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('headers', models.TextField()),
                ('synopsis', models.TextField()),
                ('naics', models.PositiveIntegerField()),
                ('period', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('incumbent', models.TextField()),
                ('matched', models.TextField()),
            ],
        ),
    ]
