# Generated by Django 2.2 on 2019-04-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_contract_app', '0002_delete_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword1', models.CharField(max_length=200)),
                ('keyword2', models.CharField(max_length=200)),
                ('keyword3', models.CharField(max_length=200)),
                ('keyword4', models.CharField(max_length=200)),
                ('keyword5', models.CharField(max_length=200)),
                ('keyword6', models.CharField(max_length=200)),
            ],
        ),
    ]
