# Generated by Django 2.2 on 2019-04-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_contract_app', '0003_keyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
